version: '3'
services:
    laravel.test:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: mfcmatheus/sail-sqlsrv-boilerplate
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail

    sqlsrv:
        image: 'mcr.microsoft.com/mssql/server:2022-latest'
        ports:
            - '${FORWARD_SQLSRV_PORT:-1433}:1433'
        environment:
            SA_PASSWORD: '${DB_PASSWORD}'
            ACCEPT_EULA: 'Y'
            MSSQL_PID: 'Express'
            MSSQL_COLLATION: 'SQL_Latin1_General_CP1_CI_AS'
            MSSQL_DATABASE: '${DB_DATABASE}'
            MSSQL_USER: '${DB_USERNAME}'
            MSSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'sqlsrv:/var/opt/mssql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "${DB_USERNAME}", "-P", "${DB_PASSWORD}", "-Q", "SELECT 1"]
            retries: 3
            timeout: 5s

networks:
    sail:
        driver: bridge

volumes:
    sqlsrv:
        driver: local
